paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    url: /[full_slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/content/posts
    icon: event_available
    url: /[collection]/[slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.mdx
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
  spec:
    path: src/content/spec
    icon: spa
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: src/data
    icon: data_usage
    disable_url: true
    preview:
    _inputs:
      $.title:
        comment: The title of this website in the browser tab.
        cascade: true
      $.subtitle:
        comment: >-
          The subtitle of this website in the browser tab. This will suffix the
          title using a hyphen.
        cascade: true
      $.siteStartDate:
        comment: >-
          The date the site started running, used by the site statistics
          component to calculate the number of days it has been running.
        cascade: true
      $.themeColor.hue:
        comment: >-
          The default hue of the theme color, ranging from 0 to 360. For
          example: Red: 0, Cyan: 200, Blue-green: 250, Pink: 345
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  $.title:
    type: text
    options:
      required: true
    cascade: true
  $.published:
    type: datetime
    cascade: true
  $.description:
    type: textarea
    options:
      show_count: true
      required: true
    cascade: true
  $.encrypted:
    type: switch
    comment: Password protect this post.
    cascade: true
  $.pinned:
    type: switch
    cascade: true
  $.tags:
    type: multiselect
    cascade: true
  $.password:
    type: text
    options: {}
    cascade: true
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
