paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    url: /[full_slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/content/posts
    icon: event_available
    url: /[collection]/[slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  spec:
    path: src/content/spec
    icon: spa
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  $.title:
    type: text
    options:
      required: true
    cascade: true
  $.published:
    type: datetime
    cascade: true
  $.description:
    type: textarea
    options:
      show_count: true
      required: true
    cascade: true
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
