paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    url: /[full_slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/content/posts
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: src/data
    icon: data_usage
    disable_url: true
    _inputs:
      $.title:
        type: text
        options:
          icon:
          empty_type:
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          min_graphemes:
          min_graphemes_message:
          max_graphemes:
          max_graphemes_message:
          min_words:
          min_words_message:
          max_words:
          max_words_message:
          locale:
        comment: Add a title for the announcement box.
        cascade: true
      $.content:
        type: textarea
        options:
          empty_type:
          show_count: true
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          min_graphemes:
          min_graphemes_message:
          max_graphemes:
          max_graphemes_message:
          min_words:
          min_words_message:
          max_words:
          max_words_message:
          locale:
        cascade: true
      $.closable:
        type: switch
        comment: Can this announement be closed?
        cascade: true
      $.link.enable:
        type: switch
        cascade: true
      $.link:
        type: object
        comment: Add a button to the announcement.
        cascade: true
      $.link.text:
        type: text
        comment: Define the button text.
        cascade: true
      $.link.url:
        type: url
        comment: Define the button URL.
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
