paths:
  static: public
  uploads: public/uploads
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  posts:
    path: src/content/posts
    icon: event_available
  spec:
    path: src/content/spec
    icon: spa
