paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: browse
    url: /[full_slug]/
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  posts:
    path: src/content/posts
    icon: add_notes
    url: /[collection]/[slug]/
    disable_url: false
    _inputs:
      $.title:
        type: text
        options:
          icon:
          empty_type:
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          min_graphemes:
          min_graphemes_message:
          max_graphemes:
          max_graphemes_message:
          min_words:
          min_words_message:
          max_words:
          max_words_message:
          locale:
        cascade: true
      $.published:
        type: datetime
        cascade: true
      $.tags:
        type: multiselect
        cascade: true
      $.description:
        type: textarea
        options:
          empty_type:
          show_count: true
          required: true
          required_message:
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
          min_graphemes:
          min_graphemes_message:
          max_graphemes:
          max_graphemes_message:
          min_words:
          min_words_message:
          max_words:
          max_words_message:
          locale:
        cascade: true
      $.category:
        type: select
        cascade: true
      $.author:
        cascade: true
      $.sourceLink:
        type: url
        cascade: true
      $.draft:
        type: switch
        cascade: true
      $.password:
        type: text
        cascade: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: .cloudcannon/schemas/post.mdx
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name:
        icon:
        preview:
        _editables:
        _enabled_editors:
        _inputs:
        _select_data:
        _structures:
        create:
        new_preview_url:
commit_templates:
  - template_string: '{message}'
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
